config {
  type: "incremental",
  tags:["dashboards"],
  schema:"dataform_dashboards",
  dependOnDependencyAssertions: true,

  columns: {
    date: "The date of the event",
    row_count: "Count of rows"
  },

  bigquery: {
    partitionBy: "date",
    requirePartitionFilter: true 
  },

  
}

SELECT
  date,
  COUNT(*) AS row_count
FROM
  ${ref("events")}
WHERE
  date BETWEEN "${dataform.projectConfig.vars.startDate}"
    AND "${dataform.projectConfig.vars.endDate}"
GROUP BY
  1

